stages:
  - test
  - deploy

image: docker:latest

services:
  - docker:dind

before_script:
  ##
  ## Install ssh-agent if not already installed, it is required by Docker.
  ## (change apt-get to yum if you use an RPM-based image)
  ##
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - apk update && apk add make

  ##
  ## Run ssh-agent (inside the build environment)
  ##
  - eval $(ssh-agent -s)

  ##
  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  ##
  - echo "$SSH_PRIVATE_KEY"
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

  ##
  ## Create the SSH directory and give it the right permissions
  ##
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  ##
  ## Check identity of server to avoid Man-in-the-middle
  ##
  - ssh-keyscan 155.133.129.16 >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - docker login registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD


test_feature_branches:
  stage: test
  except:
    - develop
    - main
  script:
    - pnpm lint
    # - pnpm test-ci
  artifacts:
    when: always
    reports:
      junit:
        - ./coverage/junit.xml

deploy_staging:
  stage: deploy
  only:
      - develop
  script:
    - make build-staging
    - make push-staging

deploy_prod:
  stage: deploy
  only:
      - main
  script:
    # build iamge with dependecies
    - make build-production
    # push image to gitlab registry
    - make push-production
    # update server with new image
    - ssh admin@155.133.129.16 "
        docker login registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD && 
        docker pull registry.gitlab.com/heretictech/derive-companion-costarica:production &&
        docker run --detach --name derive_companion_costarica_tmp registry.gitlab.com/heretictech/derive-companion-costarica:production &&
        docker stop derive_companion_costarica && docker rm derive_companion_costarica || echo "no running derive_companion_costarica" &&
        docker rename derive_companion_costarica_tmp derive_companion_costarica &&
      "
