version: "3.7"
services:
  derive-companion-costarica-staging:
    build:
      context: ../../
      dockerfile: docker/developement/Dockerfile
    image: registry.gitlab.com/heretictech/derive-companion-costarica:staging
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    environment:
      VIRTUAL_HOST: sanjose-staging.derive.fm
      VIRTUAL_PORT: 4009
      LETSENCRYPT_HOST: sanjose-staging.derive.fm
      PORT: 4009
    ports:
      - "4009:4009"
    container_name: derive-companion-costarica-staging
    network_mode: bridge